// <auto-generated />
namespace DataMiner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Post_PublicationDate_Nullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Post_PublicationDate_Nullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201408081051254_Post_PublicationDate_Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
